/** This file is automatically generated. Do not edit. **/

#ifndef __UHD_GEN_HPP__
#define __UHD_GEN_HPP__

#include <Python.h>

namespace uhd {

extern const std::vector<PyMethodDef> Uhd_gen_methods;

}

#endif /** __UHD_GEN_HPP__ **/
